//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.29 at 06:28:52 AM GMT 
//

package edu.hawaii.ics.csdl.jupiter.file.review;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}ReviewIssueMeta&quot;/&gt;
 *         &lt;element ref=&quot;{}ReviewerId&quot;/&gt;
 *         &lt;element ref=&quot;{}AssignedTo&quot;/&gt;
 *         &lt;element ref=&quot;{}File&quot;/&gt;
 *         &lt;element ref=&quot;{}Type&quot;/&gt;
 *         &lt;element ref=&quot;{}Severity&quot;/&gt;
 *         &lt;element ref=&quot;{}Summary&quot;/&gt;
 *         &lt;element ref=&quot;{}Description&quot;/&gt;
 *         &lt;element ref=&quot;{}Annotation&quot;/&gt;
 *         &lt;element ref=&quot;{}Revision&quot;/&gt;
 *         &lt;element ref=&quot;{}Resolution&quot;/&gt;
 *         &lt;element ref=&quot;{}Status&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref=&quot;{}id&quot;/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class ReviewIssue {

  protected ReviewIssueMeta reviewIssueMeta;
  protected String reviewerId = "";
  protected String assignedTo = "";
  protected File file;
  protected String type = "";
  protected String severity = "";
  protected String summary = "";
  protected String description = "";
  protected String annotation = "";
  protected String revision = "";
  protected String resolution = "";
  protected String status = "";
  protected String id = "";

  /**
   * Gets the value of the reviewIssueMeta property.
   * 
   * @return possible object is {@link ReviewIssueMeta }
   * 
   */
  public ReviewIssueMeta getReviewIssueMeta() {
    return reviewIssueMeta;
  }

  /**
   * Sets the value of the reviewIssueMeta property.
   * 
   * @param value allowed object is {@link ReviewIssueMeta }
   * 
   */
  public void setReviewIssueMeta(ReviewIssueMeta value) {
    this.reviewIssueMeta = value;
  }

  /**
   * Gets the value of the reviewerId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReviewerId() {
    return reviewerId;
  }

  /**
   * Sets the value of the reviewerId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReviewerId(String value) {
    this.reviewerId = value;
  }

  /**
   * Gets the value of the assignedTo property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAssignedTo() {
    return assignedTo;
  }

  /**
   * Sets the value of the assignedTo property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAssignedTo(String value) {
    this.assignedTo = value;
  }

  /**
   * Gets the value of the file property.
   * 
   * @return possible object is {@link File }
   * 
   */
  public File getFile() {
    return file;
  }

  /**
   * Sets the value of the file property.
   * 
   * @param value allowed object is {@link File }
   * 
   */
  public void setFile(File value) {
    this.file = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the severity property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSeverity() {
    return severity;
  }

  /**
   * Sets the value of the severity property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSeverity(String value) {
    this.severity = value;
  }

  /**
   * Gets the value of the summary property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSummary() {
    return summary;
  }

  /**
   * Sets the value of the summary property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSummary(String value) {
    this.summary = value;
  }

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the annotation property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAnnotation() {
    return annotation;
  }

  /**
   * Sets the value of the annotation property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAnnotation(String value) {
    this.annotation = value;
  }

  /**
   * Gets the value of the revision property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getRevision() {
    return revision;
  }

  /**
   * Sets the value of the revision property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setRevision(String value) {
    this.revision = value;
  }

  /**
   * Gets the value of the resolution property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getResolution() {
    return resolution;
  }

  /**
   * Sets the value of the resolution property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setResolution(String value) {
    this.resolution = value;
  }

  /**
   * Gets the value of the status property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setStatus(String value) {
    this.status = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

}
