//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.28 at 09:03:28 AM GMT 
//


package edu.hawaii.ics.csdl.jupiter.file.preference;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}UpdateUrl"/>
 *         &lt;element ref="{}EnableUpdate"/>
 *         &lt;element ref="{}EnableFilter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public class General {

    protected String updateUrl;
    protected boolean enableUpdate;
    protected boolean enableFilter;

    /**
     * Gets the value of the updateUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateUrl() {
        return updateUrl;
    }

    /**
     * Sets the value of the updateUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateUrl(String value) {
        this.updateUrl = value;
    }

    /**
     * Gets the value of the enableUpdate property.
     * 
     */
    public boolean isEnableUpdate() {
        return enableUpdate;
    }

    /**
     * Sets the value of the enableUpdate property.
     * 
     */
    public void setEnableUpdate(boolean value) {
        this.enableUpdate = value;
    }

    /**
     * Gets the value of the enableFilter property.
     * 
     */
    public boolean isEnableFilter() {
        return enableFilter;
    }

    /**
     * Sets the value of the enableFilter property.
     * 
     */
    public void setEnableFilter(boolean value) {
        this.enableFilter = value;
    }

}
