//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.03.02 at 10:23:32 PM GMT 
//

package edu.hawaii.ics.csdl.jupiter.file.property;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base=&quot;{http://www.w3.org/2001/XMLSchema}anyType&quot;&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref=&quot;{}Description&quot;/&gt;
 *         &lt;element ref=&quot;{}Author&quot;/&gt;
 *         &lt;element ref=&quot;{}CreationDate&quot;/&gt;
 *         &lt;element ref=&quot;{}Directory&quot;/&gt;
 *         &lt;element ref=&quot;{}Reviewers&quot;/&gt;
 *         &lt;element ref=&quot;{}Files&quot;/&gt;
 *         &lt;element ref=&quot;{}FieldItems&quot;/&gt;
 *         &lt;element ref=&quot;{}Filters&quot;/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref=&quot;{}id&quot;/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
public class Review {

  protected String description = "";
  protected String author = "";
  protected CreationDate creationDate;
  protected String directory = "";
  protected Reviewers reviewers;
  protected Files files;
  protected FieldItems fieldItems;
  protected Filters filters;
  protected String id = "";

  /**
   * Gets the value of the description property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the author property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the value of the author property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setAuthor(String value) {
    this.author = value;
  }

  /**
   * Gets the value of the creationDate property.
   * 
   * @return possible object is {@link CreationDate }
   * 
   */
  public CreationDate getCreationDate() {
    return creationDate;
  }

  /**
   * Sets the value of the creationDate property.
   * 
   * @param value allowed object is {@link CreationDate }
   * 
   */
  public void setCreationDate(CreationDate value) {
    this.creationDate = value;
  }

  /**
   * Gets the value of the directory property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDirectory() {
    return directory;
  }

  /**
   * Sets the value of the directory property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDirectory(String value) {
    this.directory = value;
  }

  /**
   * Gets the value of the reviewers property.
   * 
   * @return possible object is {@link Reviewers }
   * 
   */
  public Reviewers getReviewers() {
    return reviewers;
  }

  /**
   * Sets the value of the reviewers property.
   * 
   * @param value allowed object is {@link Reviewers }
   * 
   */
  public void setReviewers(Reviewers value) {
    this.reviewers = value;
  }

  /**
   * Gets the value of the files property.
   * 
   * @return possible object is {@link Files }
   * 
   */
  public Files getFiles() {
    return files;
  }

  /**
   * Sets the value of the files property.
   * 
   * @param value allowed object is {@link Files }
   * 
   */
  public void setFiles(Files value) {
    this.files = value;
  }

  /**
   * Gets the value of the fieldItems property.
   * 
   * @return possible object is {@link FieldItems }
   * 
   */
  public FieldItems getFieldItems() {
    return fieldItems;
  }

  /**
   * Sets the value of the fieldItems property.
   * 
   * @param value allowed object is {@link FieldItems }
   * 
   */
  public void setFieldItems(FieldItems value) {
    this.fieldItems = value;
  }

  /**
   * Gets the value of the filters property.
   * 
   * @return possible object is {@link Filters }
   * 
   */
  public Filters getFilters() {
    return filters;
  }

  /**
   * Sets the value of the filters property.
   * 
   * @param value allowed object is {@link Filters }
   * 
   */
  public void setFilters(Filters value) {
    this.filters = value;
  }

  /**
   * Gets the value of the id property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setId(String value) {
    this.id = value;
  }

}
